<?php

namespace backend\assets;

use common\assets\AdminLte;
use common\assets\Common;
use yii\web\AssetBundle;

/**
 * Main backend application asset bundle.
 */
class AppAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';
    public $css = [
        'css/site.less',
    ];
    public $js = [
    ];
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->depends = array_merge($this->depends, [
            Common::className(),
            AdminLte::className(),
        ]);
    }
}
