<?php
/**
 * Created by PhpStorm.
 * User: wodrow
 * Date: 17-5-7
 * Time: 上午9:43
 */

namespace common\models;
use common\components\rule\Level;
use GDText\Box;
use GDText\Color;
use yii\base\Model;
use yii\db\ActiveRecord;
use yii\helpers\Url;

/**
 * Class UserInfo
 * @package common\models
 *
 * @property UserLevelRule $levelRule
 */
class UserInfo extends \common\models\tables\UserInfo
{
    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        if (!$this->nickname){
            $this->nickname = $this->user->username;
        }
        if (!$this->avatar){
            $this->avatar = substr($this->user->username, 0, 2);
        }
    }

    /**
     * @return array|null| ActiveRecord
     */
    public function getLevelRule()
    {
//        $rule = UserLevelRule::find()->where(['and', ['>', 'end', $this->level], ['<=', 'begin', $this->level]])->one();
        $rule = Level::getUserLevelRule($this->level);
        return $rule;
    }

    public function getTextAvatarUrl()
    {
        $text = $this->avatar;
        $rule = $this->levelRule->avatar_rule;
//        var_dump($rule->background->r);exit;
        $url = Url::to(['/site/avatar', 'text'=>$text, 'rule'=>$rule]);
//        var_dump($url); exit;
        return $url;
    }

    public function attributeLabels()
    {
        return [
            'id' => '编号',
            'user_id' => '用户编号',
            'nickname' => '昵称',
            'avatar' => '头像',
            'type' => '类型',
            'level' => '级别',
            'integral' => '积分',
            'treasure' => '财富',
            'qq' => 'QQ',
            'mobile' => '手机',
        ];
    }
}