<?php
/**
 * Created by PhpStorm.
 * User: wodrow
 * Date: 17-5-7
 * Time: 上午9:43
 */

namespace common\models;


class UserInfo extends \common\models\tables\UserInfo
{
    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
//        if (!$this->nickname){
//            $this->nickname = $this->user->username;
//        }
    }
}