<?php
/**
 * Created by PhpStorm.
 * User: wodrow
 * Date: 4/24/17
 * Time: 1:38 PM
 */

namespace frontend\behaviors;

use yii\filters\AccessControl;

class Check extends AccessControl
{
    public function beforeAction($action)
    {
//		var_dump(\Yii::$app->user->identity->id);exit;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}